// src/pages/config/model.js
export const PLATFORMS = [
  { key: "whatsapp", name: "WhatsApp", brand: "#25D366" },
  { key: "phone", name: "Teléfono", brand: "#0ea5e9" },
  { key: "email", name: "Email", brand: "#0ea5e9" },
  { key: "instagram", name: "Instagram", brand: "#C13584" },
  { key: "tiktok", name: "TikTok", brand: "#000000" },
  { key: "facebook", name: "Facebook", brand: "#1877F2" },
  { key: "linkedin", name: "LinkedIn", brand: "#0A66C2" },
  { key: "youtube", name: "YouTube", brand: "#FF0000" },
  { key: "website", name: "Página Web", brand: "#0ea5e9" },
  { key: "x", name: "X (Twitter)", brand: "#111111" },
  { key: "telegram", name: "Telegram", brand: "#229ED9" },
  { key: "pdf", name: "PDF", brand: "#6b7280" },
  { key: "custom", name: "Personalizado", brand: "#7c3aed" },
];

export const PLACEHOLDERS = {
  whatsapp: "https://wa.me/51999999999",
  phone: "tel:+51999999999",
  email: "mailto:tu@correo.com",
  instagram: "https://instagram.com/usuario",
  tiktok: "https://www.tiktok.com/@usuario",
  facebook: "https://facebook.com/tu.pagina",
  linkedin: "https://linkedin.com/in/usuario",
  youtube: "https://youtube.com/@canal",
  website: "https://tu-dominio.com",
  x: "https://x.com/usuario",
  telegram: "https://t.me/usuario",
  pdf: "Sube un PDF o pega una URL",
  custom: "https://enlace-o-protocolo",
};

export const DEFAULT_PROFILE = {
  title: "",
  description: "",
  align: "center",
  textColor: "#FFFFFF",
  avatarAlign: "center",
  bgMode: "image",
  bgColor: "#0f172a",
  bgColor2: "#1e3a8a",
  bgAngle: 180,
  bgImageDataUrl: "",
  overlayOpacity: 0.45,
  bgPosX: 50,
  bgPosY: 50,
  bgZoom: 100,
  btnVariant: "filled",
  btnUseBrand: false,
  btnBg: "#0f172a",
  btnText: "#ffffff",
  btnBorder: "#ffffff",
  btnBorderWidth: 2,
  btnRadius: 18,
  btnPill: true,
  btnShadow: true,
  btnAlign: "stretch",
  btnWidth: 85,
  btnContentAlign: "left",
  btnIconSide: "left",
  phoneWidth: 390,
  containerPadding: 18,
  heroOffset: 0,
  linksGap: 12,
  fontFamily: "System",
  fontSize: 16,
  avatarDataUrl: "",
  pdfDataUrl: "",
  pdfName: "",
  contactFullName: "",
  contactOrg: "",
  contactTitle: "",
  contactPhone: "",
  contactEmail: "",
  contactWebsite: "",
  contactStreet: "",
  contactCity: "",
  contactRegion: "",
  contactPostalCode: "",
  contactCountry: "",
  contactNote: "",
};

export const FONTS = [
  { label: "System", css: "" },
  { label: "Inter", css: "Inter:wght@400;600;700" },
  { label: "Poppins", css: "Poppins:wght@400;600;700" },
  { label: "Montserrat", css: "Montserrat:wght@400;600;700" },
  { label: "Raleway", css: "Raleway:wght@400;600;700" },
  { label: "Playfair Display", css: "Playfair+Display:wght@400;600;700" },
  { label: "Roboto", css: "Roboto:wght@400;700" },
];

export const STYLE_PRESETS = [
  {
    key: "claro",
    name: "Claro",
    demo: "linear-gradient(135deg,#f8fafc,#e2e8f0)",
    patch: {
      bgMode: "gradient",
      bgColor: "#f8fafc",
      bgColor2: "#e2e8f0",
      textColor: "#111827",
      btnVariant: "outline",
      btnUseBrand: false,
      btnBg: "#ffffff",
      btnText: "#111827",
      btnBorder: "#cbd5e1",
      btnShadow: true,
      fontFamily: "Inter",
    },
  },
  {
    key: "vibrante",
    name: "Vibrante",
    demo: "linear-gradient(135deg,#0ea5e9,#7c3aed)",
    patch: {
      bgMode: "gradient",
      bgColor: "#0ea5e9",
      bgColor2: "#7c3aed",
      textColor: "#ffffff",
      btnVariant: "filled",
      btnUseBrand: false,
      btnBg: "#111827",
      btnText: "#ffffff",
      btnBorder: "#111827",
      btnShadow: true,
      fontFamily: "Montserrat",
    },
  },
  {
    key: "oscuro",
    name: "Oscuro",
    demo: "linear-gradient(135deg,#0b1220,#111827)",
    patch: {
      bgMode: "solid",
      bgColor: "#0b1220",
      textColor: "#e5e7eb",
      btnVariant: "filled",
      btnUseBrand: false,
      btnBg: "#111827",
      btnText: "#e5e7eb",
      btnBorder: "#374151",
      btnShadow: false,
      fontFamily: "Roboto",
    },
  },
];